apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager # Typically in cert-manager's namespace
spec:
  acme:
    email: heweywade@hotmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token # Must exist in the same namespace as ClusterIssuer
              key: api-token
        selector:
          dnsZones:
            - "hewett.club"
