---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    # need these labels to allow it to do things (TODO yes theres better ways)
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
