apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io/
      targetRevision: v1.17.0
      helm:
        values: |
          crds:
            enabled: true
    - repoURL: git@github.com:hewey159/home-lab.git
      targetRevision: HEAD
      path: infrastructure/wade/certmanager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
