apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: git@github.com:hewey159/home-lab.git
      targetRevision: HEAD
      path: apps/base/homepage
    - repoURL: git@github.com:hewey159/home-lab.git
      targetRevision: HEAD
      path: apps/wade/homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
