apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/hewey159/home-lab.git # Your Git repo
      path: infrastructure/base/argocd-apps/longhorn # Path to the kustomization.yaml
      targetRevision: main # Your branch
      kustomize: {} # Enable Kustomize processing
    - repoURL: https://github.com/hewey159/home-lab.git
      targetRevision: HEAD
      path: infrastructure/base/longhorn
    - repoURL: https://github.com/hewey159/home-lab.git
      targetRevision: HEAD
      path: infrastructure/wade/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
