apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.1
      helm:
        values: |
          controller:
            service:
              type: NodePort
              nodePorts:
                http: 32080
                https: 32443
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
