apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  project: default
  sources:
    - chart: pihole
      repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: 2.29.1 # Replace with the pihole version you'd like to install or upgrade to
      helm:
        values: |
          # will create kubernees ingress
          ingress:
            enabled: false

          # will create kubernetes services for web admin
          serviceWeb:
            loadBalancerIP: 192.168.0.202
            type: LoadBalancer
            annotations:
              metallb.universe.tf/allow-shared-ip: pihole-svc
            
          # get the password from infisical which will set your admin password for the web inteface
          admin:
            existingSecret: "pihole-password"
            passwordKey: "PASSWORD"

          #todo do i need this to access local ips?
          DNS1:
            192.168.0.1

          #allow ads in google otherwise google search sponsered shopoing at the top sucks
          whitelist: 
            - t.myvisualiq.net
            - clickserve.dartsearch.net
            - ad.doubleclick.net
            - dartsearch.net
            - www.googletagservices.com
            - www.googletagmanager.com
            - www.googleadservices.com	

          dnsmasq:
            customDnsEntries:
              - "except-interface=nonexisting"  # Key directive to allow all origins
              - address=/mealie-test.hewett.club/192.168.0.189
              - address=/argocd.hewett.club/192.168.0.189
              - address=/longhorn.hewett.club/192.168.0.189
              - address=/secret.hewett.club/192.168.0.189
            
          # create a kubernetes service and expose
          # port 53 outside of cluster on the local network
          serviceDns:
            loadBalancerIP: 192.168.0.202
            type: LoadBalancer
            annotations:
              metallb.universe.tf/allow-shared-ip: pihole-svc

          adlists:
            - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/multi.txt

          replicaCount: 1

    - repoURL: git@github.com:hewey159/home-lab.git
      targetRevision: HEAD
      path: infrastructure/wade/pihole
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
