apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speed-test
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: git@github.com:hewey159/home-lab.git
      targetRevision: HEAD
      path: apps/base/speed-test
    - repoURL: git@github.com:hewey159/home-lab.git
      targetRevision: HEAD
      path: apps/wade/speed-test
  destination:
    server: https://kubernetes.default.svc
    namespace: speed-test

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
