# Expose web interface via Ingress
ingress:
  enabled: false
  hosts:
    - pihole.hewett.club

# Web service (ClusterIP, exposed via Ingress)
serviceWeb:
  type: ClusterIP

# DNS service (LoadBalancer with static IP)
serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.153 # MetalLB will assign this IP
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-dns" # Optional: Share IP if needed

# Persistence with Longhorn
persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"

# Affinity rules to target your two nodes
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: home
              operator: In
              values: ["true"]
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: ["pihole"]
          topologyKey: kubernetes.io/hostname
