---
# Mealie Persistent Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-pvc
  annotations:
    longhorn.io/recurring-job-group: '["daily-backup"]'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-ad18e1f1-bcf9-456c-b054-94eae52fc8d0

---
# PostgreSQL Persistent Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pgdata-pvc
  annotations:
    longhorn.io/recurring-job-group: '["daily-backup"]'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-9fecbff1-f7b1-4237-90fd-bf2655ad80ef
