---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres-infisical-secret
  namespace: mealie
  labels:
    label-to-be-passed-to-managed-secret: sample-value
  annotations:
    example.com/annotation-to-be-passed-to-managed-secret: "sample-value"
spec:
  hostAPI: https://secret.hewett.club/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: mealie-9l-b4 # <-- project slug
        envSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: "/" # Root is "/"
      credentialsRef:
        secretName: universal-auth-credentials # <-- name of the Kubernetes secret that stores our machine identity credentials
        secretNamespace: mealie # <-- namespace of the Kubernetes secret that stores our machine identity credentials
  managedKubeSecretReferences:
    - secretName: mealie-secret
      secretNamespace: mealie # todo can this just be whatever, the same as the other k8s resources?
      creationPolicy: "Owner" #owner otherwise argocd will prune this resource
      template:
        includeAllSecrets: true
