apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  # settings.yaml: ""
  settings.template.yaml: |
    providers:
      longhorn:
        url: https://longhorn.hewett.club
        username: ${LONGHORN_USERNAME}
        password: ${LONGHORN_PASSWORD}
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.template.yaml: |
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
    - Plex:
        - something:
            href: http://localhost/
            description: Homepage is 😎
            widget:
              type: plex
              url: http://192.168.0.21:32400
              key: ${PLEX_TOKEN} 
              fields: ["streams", "albums", "movies", "tv"]
  widgets.template.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    # - search:
    #     provider: duckduckgo
    #     target: _blank
    # - longhorn:
    #   # Show the expanded view
    #   expanded: true
    #   # Shows a node representing the aggregate values
    #   total: true
    #   # Shows the node names as labels
    #   labels: true
    #   # Show the nodes
    #   nodes: false
    - datetime:
        text_size: xl
        format:
          timeStyle: short

  docker.yaml: ""
