apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  # settings.yaml: ""
  settings.template.yaml: |
    providers:
      longhorn:
        url: https://longhorn.hewett.club
        username: ${LONGHORN_USERNAME}
        password: ${LONGHORN_PASSWORD}
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.template.yaml: |
    - Media:
        - Plex:
            icon: plex.svg
            href: http://192.168.0.21:32400
            widget:
              type: plex
              url: http://192.168.0.21:32400
              key: ${PLEX_TOKEN} 
              fields: ["streams", "albums", "movies", "tv"]
        - Sonarr:
            icon: sonarr.svg
            href: http://192.168.0.21:8989
            widget:
              type: sonarr
              url: http://192.168.0.21:8989
              key: ${SONAR_KEY} 
              enableQueue: true # optional, defaults to false
        - Radarr:
            icon: radarr.svg
            href: http://192.168.0.21:7878
            widget:
              type: radarr
              url: http://192.168.0.21:7878
              key: ${RADARR_KEY} 
              enableQueue: true # optional, defaults to false
        - Transmission:
            icon: transmission.svg
            href: http://192.168.0.21:9091
            widget:
              type: transmission
              url: http://192.168.0.21:9091
        - Overseerr:
            icon: overseerr.svg
            href: https://movies.hewett.club
            widget:
              type: overseerr
              url: https://movies.hewett.club
              key: ${OVERSEERR_KEY} 
        - CalibreWeb:
            icon: calibre-web.svg
            href: http://192.168.0.21:8083
            widget:
              type: calibreweb
              url: http://192.168.0.21:8083
              username: ${CALIBRE_USERNAME}
              password: ${CALIBRE_PASSWORD}

  widgets.template.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    # - search:
    #     provider: duckduckgo
    #     target: _blank
    # - longhorn:
    #   # Show the expanded view
    #   expanded: true
    #   # Shows a node representing the aggregate values
    #   total: true
    #   # Shows the node names as labels
    #   labels: true
    #   # Show the nodes
    #   nodes: false
    - datetime:
        text_size: xl
        format:
          timeStyle: short

  docker.yaml: ""
