---
# homepage Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/homepage-recipes/homepage:v1.1.1
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: hewett.club # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: homepage-storage
              mountPath: /app/config
      volumes:
        - name: homepage-storage
          persistentVolumeClaim:
            claimName: homepage-storage
