apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      initContainers:
        - name: env-substitute
          image: alpine
          command:
            - sh
            - -c
            - |
              apk add --no-cache gettext && \
              envsubst < /config-tmpl/settings.template.yaml > /config/settings.yaml && \
              envsubst < /config-tmpl/widgets.template.yaml > /config/widgets.yaml && \
              envsubst < /config-tmpl/services.template.yaml > /config/services.yaml
          env:
            - name: LONGHORN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: longhorn-secret
                  key: BASIC_AUTH_USERNAME
            - name: LONGHORN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: longhorn-secret
                  key: BASIC_AUTH_PASSWORD
            - name: PLEX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: plex-secret
                  key: PLEX_TOKEN
            - name: SONAR_KEY
              valueFrom:
                secretKeyRef:
                  name: sonarr-secret
                  key: SONAR_KEY
            - name: RADARR_KEY
              valueFrom:
                secretKeyRef:
                  name: radarr-secret
                  key: RADARR_KEY
            - name: OVERSEERR_KEY
              valueFrom:
                secretKeyRef:
                  name: overseerr-secret
                  key: OVERSEERR_KEY
            - name: CALIBRE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: calibre-secret
                  key: CALIBRE_USERNAME
            - name: CALIBRE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calibre-secret
                  key: CALIBRE_PASSWORD
          volumeMounts:
            - name: config-template
              mountPath: /config-tmpl
            - name: config-processed
              mountPath: /config
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v1.1.1"
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.hewett.club
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-processed
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: homepage-config
              mountPath: /app/config/custom.js
              subPath: custom.js
            - name: homepage-config
              mountPath: /app/config/custom.css
              subPath: custom.css
            - name: homepage-config
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: homepage-config
              mountPath: /app/config/docker.yaml
              subPath: docker.yaml
            - name: homepage-config
              mountPath: /app/config/kubernetes.yaml
              subPath: kubernetes.yaml
            - name: config-processed
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: config-processed
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: config-template
          configMap:
            name: homepage
        - name: config-processed
          emptyDir: {}
        - name: logs
          emptyDir: {}
