---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: homepage
spec:
  hostAPI: https://secret.hewett.club
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-aaz-9 # <-- project slug
        envSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: "/Homepage" # Root is "/"
      credentialsRef:
        secretName: universal-auth-credentials # <-- name of the Kubernetes secret that stores our machine identity credentials
        secretNamespace: infisical # <-- namespace of the Kubernetes secret that stores our machine identity credentials
  managedKubeSecretReferences:
    - secretName: homepage
      secretNamespace: homepage # todo can this just be whatever, the same as the other k8s resources?
      creationPolicy: "Owner" #owner otherwise argocd will prune this resource
      template:
        includeAllSecrets: true
