---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  cron: "0 0 * * *" # Runs daily at midnight
  task: "backup"
  groups:
    - daily-backup
  retain: 2
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-snapshot
  namespace: longhorn-system
spec:
  cron: "0 0 * * *" # Runs daily at midnight
  task: "snapshot"
  groups:
    - daily-backup
  retain: 4
  concurrency: 1
