---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-tls
spec:
  secretName: pihole-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pihole.hewett.club
